Repository swyp-app-team-4/boombim-backend-api, pull requests merged in 2025-09, with the labels that each got.

#63 [Feat] 사용자 장소 상세 API 구현 및 무한 스크롤 적용
  .gitignore
  src/main/java/boombimapi/domain/congestion/dto/response/MemberCongestionItemResponse.java
  src/main/java/boombimapi/domain/congestion/repository/MemberCongestionRepository.java
  src/main/java/boombimapi/domain/place/api/MemberPlaceController.java
  src/main/java/boombimapi/domain/place/application/MemberPlaceService.java
  src/main/java/boombimapi/domain/place/dto/request/ResolveMemberPlaceRequest.java
  src/main/java/boombimapi/domain/place/dto/response/member/GetMemberPlaceDetailResponse.java
  src/main/java/boombimapi/domain/place/dto/response/member/MemberPlaceSummaryResponse.java
  src/main/java/boombimapi/domain/place/dto/response/member/ResolveMemberPlaceResponse.java
  src/main/java/boombimapi/domain/place/dto/response/node/ViewportPlaceNodeResponse.java
  src/main/java/boombimapi/domain/place/entity/MemberPlace.java
  src/main/java/boombimapi/domain/vote/application/service/impl/VoteServiceImpl.java
  src/main/java/boombimapi/domain/vote/presentation/dto/req/VoteRegisterReq.java
  src/main/java/boombimapi/global/response/ResponseMessage.java
  src/main/resources/application-prod.yml
Labels: ✨ Feature

#65 [Feat] 공식 장소 Response에 `imageUrl` 추가 및 누락된 Swagger 어노테이션 추가
  src/main/java/boombimapi/domain/congestion/api/MemberCongestionController.java
  src/main/java/boombimapi/domain/favorite/api/FavoriteController.java
  src/main/java/boombimapi/domain/place/application/OfficialPlaceService.java
  src/main/java/boombimapi/domain/place/dto/response/ViewportResponse.java
  src/main/java/boombimapi/domain/place/dto/response/official/OfficialPlaceOverviewResponse.java
  src/main/java/boombimapi/global/dto/Coordinate.java
  src/main/resources/application-prod.yml
Labels: ✨ Feature

#67 [Feat] CLOVA Studio를 사용해 혼잡도 메시지 자동 작성 기능 구현
  src/main/java/boombimapi/domain/clova/api/ClovaController.java
  src/main/java/boombimapi/domain/clova/application/ClovaService.java
  src/main/java/boombimapi/domain/clova/dto/request/ChatContent.java
  src/main/java/boombimapi/domain/clova/dto/request/ChatMessage.java
  src/main/java/boombimapi/domain/clova/dto/request/ClovaChatRequest.java
  src/main/java/boombimapi/domain/clova/dto/request/GenerateCongestionMessageRequest.java
  src/main/java/boombimapi/domain/clova/dto/response/ClovaContent.java
  src/main/java/boombimapi/domain/clova/dto/response/ClovaMessage.java
  src/main/java/boombimapi/domain/clova/dto/response/ClovaResponse.java
  src/main/java/boombimapi/domain/clova/dto/response/ClovaResult.java
  src/main/java/boombimapi/domain/clova/dto/response/GenerateCongestionMessageResponse.java
  src/main/java/boombimapi/domain/clova/infrastructure/ClovaCongestionMessageClient.java
  src/main/java/boombimapi/domain/clova/infrastructure/parser/ClovaParser.java
  src/main/java/boombimapi/domain/clova/infrastructure/parser/DefaultClovaParser.java
  src/main/java/boombimapi/domain/congestion/repository/MemberCongestionRepository.java
  src/main/java/boombimapi/global/config/WebConfig.java
  src/main/java/boombimapi/global/properties/ClovaCongestionMessageProperties.java
  src/main/java/boombimapi/global/properties/ClovaGenerationProperties.java
  src/main/java/boombimapi/global/properties/ClovaPromptProperties.java
  src/main/java/boombimapi/global/response/ResponseMessage.java
Labels: ✨ Feature

#69 [Hotfix] 중복 메서드 제거
  src/main/java/boombimapi/domain/congestion/repository/MemberCongestionRepository.java
Labels: 🐞 Bug

#71 [Feat] CLOVA Studio용 환경변수 추가
  src/main/resources/application-prod.yml
Labels: ✨ Feature

#75 [Fix] SecurityConfig Prometheus and Grafana monitoring
  src/main/java/boombimapi/global/config/SecurityConfig.java
Labels: 🔨 Update

#80 [Fix] 혼잡도 메시지 자동 생성 프롬프트 깨짐 현상
  src/main/java/boombimapi/global/properties/ClovaPromptProperties.java
  src/main/resources/application-prod.yml
Labels: 🐞 Bug

#86 [Feat] 실시간으로 붐비는 공식 장소 Top 5 조회 기능 구현
  src/main/java/boombimapi/domain/congestion/entity/OfficialCongestion.java
  src/main/java/boombimapi/domain/congestion/repository/OfficialCongestionRepository.java
  src/main/java/boombimapi/domain/congestion/repository/OfficialPlaceCongestionRankProjection.java
  src/main/java/boombimapi/domain/place/api/OfficialPlaceController.java
  src/main/java/boombimapi/domain/place/application/OfficialPlaceService.java
  src/main/java/boombimapi/domain/place/dto/response/ViewportResponse.java
  src/main/java/boombimapi/domain/place/dto/response/official/CongestedOfficialPlaceResponse.java
  src/main/java/boombimapi/domain/place/dto/response/official/NearbyOfficialPlaceResponse.java
  src/main/java/boombimapi/domain/place/dto/response/official/OfficialPlaceOverviewResponse.java
  src/main/java/boombimapi/domain/place/entity/OfficialPlace.java
  src/main/java/boombimapi/domain/place/repository/OfficialPlaceRepository.java
  src/main/java/boombimapi/domain/place/repository/projection/NearbyOfficialPlaceProjection.java
  src/main/java/boombimapi/global/response/ResponseMessage.java
  src/main/resources/application-prod.yml
Labels: ✨ Feature

#88 Feat#61 API 오류 개선
  src/main/java/boombimapi/domain/member/presentation/controller/AdminController.java
  src/main/java/boombimapi/domain/search/application/impl/SearchServiceImpl.java
  src/main/java/boombimapi/domain/vote/application/service/impl/VoteServiceImpl.java
  src/main/java/boombimapi/global/infra/exception/error/ErrorCode.java
  src/main/resources/application-prod.yml
Labels: 🔨 Update

#89 [Chore] Redis 볼륨 추가
  docker-compose.yml
Labels: 🔨 Update

#92 [Fix] 인근 한산한 공식 장소 조회 시 법정동(legalDong) 필드에 값이 누락되는 문제 해결
  src/main/java/boombimapi/domain/place/api/OfficialPlaceController.java
  src/main/java/boombimapi/domain/place/application/OfficialPlaceService.java
  src/main/java/boombimapi/domain/place/dto/response/official/NearbyNonCongestedOfficialPlaceResponse.java
  src/main/java/boombimapi/domain/place/repository/OfficialPlaceRepository.java
  src/main/java/boombimapi/domain/place/repository/projection/NearbyNonCongestedOfficialPlaceProjection.java
Labels: 🐞 Bug

#94 [Chore] Add persistent volumes for Prometheus and Grafana, remove unn…
  docker-compose.yml
Labels: 🔨 Update

#96 [Refactor] Response에 누락된 필드 추가
  src/main/java/boombimapi/domain/congestion/dto/response/MemberCongestionItemResponse.java
  src/main/java/boombimapi/domain/place/application/MemberPlaceService.java
  src/main/java/boombimapi/domain/place/dto/response/node/ViewportPlaceNodeResponse.java
Labels: 🔨 Update

#98 Refactor#97 투표 중복자 DTO 통일
  src/main/java/boombimapi/domain/member/presentation/dto/member/res/mypage/MPVoteRes.java
  src/main/java/boombimapi/domain/vote/application/service/impl/VoteServiceImpl.java
  src/main/java/boombimapi/domain/vote/presentation/dto/res/list/MyVoteRes.java
  src/main/java/boombimapi/domain/vote/presentation/dto/res/list/VoteRes.java
Labels: 🔨 Update

#100 Refactor#97 vote duplication api
  docker-compose.yml
  src/main/java/boombimapi/domain/vote/application/service/impl/VoteServiceImpl.java
Labels: 🔨 Update

#102 [Fix] Modify SecurityConfig Logout
  src/main/java/boombimapi/global/config/SecurityConfig.java
Labels: 🔨 Update

#103 [Fix] Delete FCM token on MemberDelete
  src/main/java/boombimapi/domain/member/application/service/impl/MemberServiceImpl.java
Labels: 🔨 Update

#108 [Refactor] 공식 장소 상세 조회 Response에 필드 추가
  src/main/java/boombimapi/domain/place/application/OfficialPlaceService.java
  src/main/java/boombimapi/domain/place/dto/response/official/OfficialPlaceOverviewResponse.java
Labels: 🔨 Update

#114 [Fix] `CustomSecurityLogger`의 중복 등록 제거
  src/main/java/boombimapi/global/config/SecurityConfig.java
Labels: 🐞 Bug

#120 [Fix] Remove 300m restriction
  src/main/java/boombimapi/domain/vote/application/service/impl/VoteServiceImpl.java
Labels: 🔨 Update

#123 [Fix] Ensure vote owner profile is included before participants
  src/main/java/boombimapi/domain/member/application/service/impl/MemberServiceImpl.java
  src/main/java/boombimapi/domain/vote/application/service/impl/VoteServiceImpl.java
Labels: 🔨 Update
