Repository swyp-app-team-4/boombim-backend-api, pull requests merged in 2025-08, with the labels that each got.

#8 CICD 배포 작업 그리고 앱용 소셜로그인 구현 했습니다.
  .github/workflows/deploy.yml
  src/main/java/boombimapi/domain/oauth2/application/service/CreateAccessTokenAndRefreshTokenService.java
  src/main/java/boombimapi/domain/oauth2/application/service/OAuth2Service.java
  src/main/java/boombimapi/domain/oauth2/application/service/ReissueService.java
  src/main/java/boombimapi/domain/oauth2/application/service/SocialLoginService.java
  src/main/java/boombimapi/domain/oauth2/application/service/impl/CreateAccessTokenAndRefreshTokenServiceImpl.java
  src/main/java/boombimapi/domain/oauth2/application/service/impl/auth/ReissueServiceImpl.java
  src/main/java/boombimapi/domain/oauth2/application/service/impl/oauth/AppleOAuth2ServiceImpl.java
  src/main/java/boombimapi/domain/oauth2/application/service/impl/oauth/KakaoOAuth2ServiceImpl.java
  src/main/java/boombimapi/domain/oauth2/application/service/impl/oauth/NaverOAuth2ServiceImpl.java
  src/main/java/boombimapi/domain/oauth2/application/service/impl/oauth/SocialLoginServiceImpl.java
  src/main/java/boombimapi/domain/oauth2/infra/AppleJwtUtils.java
  src/main/java/boombimapi/domain/oauth2/infra/filter/BoombimJWTFilter.java
  src/main/java/boombimapi/domain/oauth2/presentation/controller/ReissueController.java
  src/main/java/boombimapi/domain/oauth2/presentation/controller/SocialLoginController.java
  src/main/java/boombimapi/domain/oauth2/presentation/dto/req/SocialTokenRequest.java
  src/main/java/boombimapi/domain/oauth2/presentation/dto/res/LoginToken.java
  src/main/java/boombimapi/domain/oauth2/presentation/dto/res/apple/ApplePublicKey.java
  src/main/java/boombimapi/domain/oauth2/presentation/dto/res/apple/ApplePublicKeys.java
  src/main/java/boombimapi/domain/oauth2/presentation/dto/res/apple/AppleTokenResponse.java
  src/main/java/boombimapi/domain/oauth2/presentation/dto/res/naver/NaverTokenResponse.java
  src/main/java/boombimapi/domain/oauth2/presentation/dto/res/naver/NaverUserResponse.java
  src/main/java/boombimapi/domain/oauth2/presentation/dto/res/oatuh/KakaoTokenResponse.java
  src/main/java/boombimapi/domain/oauth2/presentation/dto/res/oatuh/KakaoUserResponse.java
  src/main/java/boombimapi/domain/user/domain/repository/UserRepository.java
  src/main/java/boombimapi/global/config/SecurityConfig.java
  src/main/java/boombimapi/global/infra/exception/error/ErrorCode.java
  src/main/java/boombimapi/global/infra/feignclient/ios/AppleOAuth2FeignClient.java
  src/main/java/boombimapi/global/infra/feignclient/ios/AppleOAuth2FeignConfig.java
  src/main/java/boombimapi/global/infra/feignclient/kakao/KakaoOAuth2URLFeignClient.java
  src/main/java/boombimapi/global/infra/feignclient/kakao/KakaoOAuth2UserFeignClient.java
  src/main/java/boombimapi/global/infra/feignclient/naver/NaverOAuth2URLFeignClient.java
  src/main/java/boombimapi/global/infra/feignclient/naver/NaverOAuth2UserFeignClient.java
Labels: ✨ Feature

#12 [Refactor] `.gitignore`에 `application-dev.yml` 추가 작업
  .gitignore
  src/main/resources/application-dev.yml
Labels: 🔨 Update

#13 [Feat] 뷰포트 내에 위치한 공식 장소들의 좌표를 리스트로 반환하는 기능 구현
  .gitignore
  src/main/java/boombimapi/domain/congestion/domain/entity/CongestionLevel.java
  src/main/java/boombimapi/domain/congestion/domain/entity/OfficialCongestion.java
  src/main/java/boombimapi/domain/congestion/domain/entity/OfficialCongestionDemographics.java
  src/main/java/boombimapi/domain/congestion/domain/entity/OfficialCongestionForecast.java
  src/main/java/boombimapi/domain/place/application/service/PlaceService.java
  src/main/java/boombimapi/domain/place/application/service/impl/OfficialPlaceServiceImpl.java
  src/main/java/boombimapi/domain/place/domain/entity/OfficialPlace.java
  src/main/java/boombimapi/domain/place/domain/repository/OfficialPlaceRepository.java
  src/main/java/boombimapi/domain/place/presentation/controller/OfficialPlaceController.java
  src/main/java/boombimapi/domain/place/presentation/dto/common/Coordinate.java
  src/main/java/boombimapi/domain/place/presentation/dto/request/Viewport.java
  src/main/java/boombimapi/domain/place/presentation/dto/response/MapMarker.java
  src/main/java/boombimapi/global/response/BaseResponse.java
  src/main/java/boombimapi/global/response/ResponseMessage.java
  src/main/resources/application.yml
Labels: ✨ Feature

#15 [Hotfix] `application-prod.yml` 내 schema 설정 업데이트
  src/main/resources/application-prod.yml
Labels: 🐞 Bug

#17 [Feat] 특정 공식 장소의 실시간 공식 혼잡도를 조회하는 API 구현 및 혼잡도 도메인 부분적으로 CQRS 도입
  build.gradle
  src/main/java/boombimapi/domain/congestion/common/entity/CongestionLevel.java
  src/main/java/boombimapi/domain/congestion/official/entity/OfficialCongestion.java
  src/main/java/boombimapi/domain/congestion/official/entity/OfficialCongestionDemographics.java
  src/main/java/boombimapi/domain/congestion/official/entity/OfficialCongestionForecast.java
  src/main/java/boombimapi/domain/congestion/official/query/controller/OfficialCongestionQueryController.java
  src/main/java/boombimapi/domain/congestion/official/query/dto/OfficialCongestionResponse.java
  src/main/java/boombimapi/domain/congestion/official/query/repository/OfficialCongestionQueryRepository.java
  src/main/java/boombimapi/domain/congestion/official/query/service/OfficialCongestionQueryService.java
  src/main/java/boombimapi/domain/place/application/service/OfficialPlaceService.java
  src/main/java/boombimapi/domain/place/application/service/PlaceService.java
  src/main/java/boombimapi/domain/place/presentation/controller/OfficialPlaceController.java
  src/main/java/boombimapi/domain/place/presentation/dto/request/ViewportRequest.java
  src/main/java/boombimapi/domain/place/presentation/dto/response/MapMarkerResponse.java
  src/main/java/boombimapi/global/config/QuerydslConfig.java
  src/main/java/boombimapi/global/infra/exception/error/ErrorCode.java
  src/main/java/boombimapi/global/response/ResponseMessage.java
Labels: ✨ Feature

#22 [Feat] 뷰포트 내 공식 장소 조회 시 사용자 위치 기반 직선 거리순 정렬하여 반환
  src/main/java/boombimapi/domain/congestion/official/entity/OfficialCongestion.java
  src/main/java/boombimapi/domain/congestion/official/entity/OfficialCongestionForecast.java
  src/main/java/boombimapi/domain/congestion/official/query/controller/OfficialCongestionQueryController.java
  src/main/java/boombimapi/domain/congestion/official/query/dto/response/OfficialCongestionResponse.java
  src/main/java/boombimapi/domain/congestion/official/query/repository/OfficialCongestionQueryRepository.java
  src/main/java/boombimapi/domain/congestion/official/query/service/OfficialCongestionQueryService.java
  src/main/java/boombimapi/domain/place/application/service/OfficialPlaceService.java
  src/main/java/boombimapi/domain/place/domain/repository/OfficialPlaceRepository.java
  src/main/java/boombimapi/domain/place/official/entity/OfficialPlace.java
  src/main/java/boombimapi/domain/place/official/query/controller/OfficialPlaceQueryController.java
  src/main/java/boombimapi/domain/place/official/query/dto/request/ViewportRequest.java
  src/main/java/boombimapi/domain/place/official/query/dto/response/MapMarkerResponse.java
  src/main/java/boombimapi/domain/place/official/query/repository/OfficialPlaceQueryRepository.java
  src/main/java/boombimapi/domain/place/official/query/service/OfficialPlaceQueryService.java
  src/main/java/boombimapi/domain/place/presentation/dto/request/ViewportRequest.java
  src/main/java/boombimapi/domain/place/presentation/dto/response/MapMarkerResponse.java
  src/main/java/boombimapi/domain/place/shared/dto/Coordinate.java
  src/main/java/boombimapi/domain/place/shared/dto/PlaceInfo.java
  src/main/java/boombimapi/global/constant/PlaceConstant.java
Labels: ✨ Feature

#37 createdAt 수동 설정하기
  src/main/java/boombimapi/domain/alarm/domain/entity/alarm/Alarm.java
  src/main/java/boombimapi/domain/alarm/domain/entity/alarm/AlarmRecipient.java
  src/main/java/boombimapi/domain/alarm/domain/entity/fcm/FcmToken.java
  src/main/java/boombimapi/domain/member/domain/entity/Member.java
Labels: 🐞 Bug

#38 [Fix] Prevent notifications when list is empty
  src/main/java/boombimapi/global/infra/scheduled/SchedulerService.java
Labels: 🐞 Bug

#39 Refactor#1 500m -> 100m 변경
  src/main/java/boombimapi/domain/vote/application/service/impl/VoteServiceImpl.java
  src/main/java/boombimapi/global/infra/exception/error/ErrorCode.java
Labels: 🔨 Update

#42 Refactor#41 mypage api 개선하기
  src/main/java/boombimapi/domain/alarm/application/service/AlarmService.java
  src/main/java/boombimapi/domain/alarm/application/service/impl/AlarmServiceImpl.java
  src/main/java/boombimapi/domain/alarm/domain/repository/FcmTokenRepository.java
  src/main/java/boombimapi/domain/alarm/presentation/controller/AlarmController.java
  src/main/java/boombimapi/domain/member/application/service/impl/MemberServiceImpl.java
  src/main/java/boombimapi/domain/member/domain/entity/Member.java
  src/main/java/boombimapi/domain/member/presentation/controller/MemberController.java
  src/main/java/boombimapi/domain/member/presentation/dto/member/res/mypage/MPVoteRes.java
  src/main/java/boombimapi/domain/oauth2/application/service/impl/CreateAccessTokenAndRefreshTokenServiceImpl.java
  src/main/java/boombimapi/domain/oauth2/application/service/impl/auth/ReissueServiceImpl.java
  src/main/java/boombimapi/domain/oauth2/application/service/impl/oauth/SocialLoginServiceImpl.java
  src/main/java/boombimapi/domain/oauth2/presentation/controller/SocialLoginController.java
  src/main/java/boombimapi/domain/oauth2/presentation/dto/res/LoginToken.java
  src/main/java/boombimapi/domain/vote/application/service/impl/VoteServiceImpl.java
  src/main/java/boombimapi/domain/vote/presentation/dto/res/list/MyVoteRes.java
  src/main/java/boombimapi/domain/vote/presentation/dto/res/list/VoteRes.java
Labels: 🔨 Update

#50 Feat#12 region api
  src/main/java/boombimapi/domain/member/application/service/MemberService.java
  src/main/java/boombimapi/domain/member/application/service/impl/MemberServiceImpl.java
  src/main/java/boombimapi/domain/member/domain/entity/Member.java
  src/main/java/boombimapi/domain/member/domain/entity/MemberLeave.java
  src/main/java/boombimapi/domain/member/domain/repository/MemberLeaveRepository.java
  src/main/java/boombimapi/domain/member/presentation/controller/MemberController.java
  src/main/java/boombimapi/domain/member/presentation/dto/member/req/MemberLeaveReq.java
  src/main/java/boombimapi/domain/member/presentation/dto/member/res/ProfileRes.java
  src/main/java/boombimapi/domain/oauth2/presentation/controller/ReissueController.java
  src/main/java/boombimapi/domain/region/application/service/impl/RegionServiceImpl.java
  src/main/java/boombimapi/domain/region/domain/entity/Region.java
  src/main/java/boombimapi/domain/region/presentation/dto/res/RegionRes.java
  src/main/java/boombimapi/domain/vote/application/service/impl/VoteServiceImpl.java
  src/main/java/boombimapi/global/infra/exception/error/ErrorCode.java
Labels: 🔨 Update

#51 Refactor#2 alarm performance
  build.gradle
  src/main/java/boombimapi/domain/alarm/application/consumer/EndVoteWorker.java
  src/main/java/boombimapi/domain/alarm/application/consumer/PushWorker.java
  src/main/java/boombimapi/domain/alarm/application/messaging/EndVoteMessage.java
  src/main/java/boombimapi/domain/alarm/application/messaging/NotifyMessage.java
  src/main/java/boombimapi/domain/alarm/application/service/impl/AlarmServiceImpl.java
  src/main/java/boombimapi/domain/alarm/application/service/impl/FcmSender.java
  src/main/java/boombimapi/domain/alarm/application/service/impl/FcmServiceImpl.java
  src/main/java/boombimapi/domain/alarm/domain/entity/alarm/Alarm.java
  src/main/java/boombimapi/domain/alarm/domain/entity/alarm/type/AlarmStatus.java
  src/main/java/boombimapi/domain/alarm/infra/messaging/PushProducer.java
  src/main/java/boombimapi/domain/member/domain/entity/Member.java
  src/main/java/boombimapi/global/aop/TimeTraceAop.java
  src/main/java/boombimapi/global/config/RabbitMQConfig.java
  src/main/java/boombimapi/global/infra/init/member/MemberDataInitializer.java
  src/main/java/boombimapi/global/infra/scheduled/SchedulerService.java
  src/main/resources/application-prod.yml
Labels: ✨ Feature

#54 [Fix] Update RabbitMQ config
  src/main/java/boombimapi/domain/alarm/infra/messaging/PushProducer.java
  src/main/java/boombimapi/domain/vote/application/service/impl/VoteServiceImpl.java
  src/main/java/boombimapi/global/config/RabbitMQConfig.java
Labels: 🔨 Update
